Repository Nexters/If-Web, pull requests merged in 2021-02, with the labels that each got.

#12 폴라로이드 컴포넌트 구현 및 .env 설정
  .env-template
  .gitignore
  package.json
  src/pages/App.tsx
  src/pages/main/AddButton.tsx
  src/pages/main/Story.tsx
  src/pages/main/index.tsx
  src/pages/main/interface.ts
  src/styles/global.ts
  src/types/index.ts
  src/utils/formatter.ts
  webpack.common.js
  yarn.lock
Labels: feature

#16 스크롤 바 제거
  src/styles/global.ts
Labels: feature

#13 국가별 앨범 페이지 마크업 / 공통 레이아웃 컴포넌트 / fontSizes 테마
  src/components/AlbumTitle.tsx
  src/components/NationList.tsx
  src/components/NationListItem.tsx
  src/components/NationListTitle.tsx
  src/components/common/Layout.tsx
  src/pages/Album.tsx
  src/pages/App.tsx
  src/styles/theme.ts
Labels: feature

#14 Header 추가
  .DS_Store
  assets/album.svg
  assets/arrow.svg
  assets/feed.svg
  assets/mypage.svg
  assets/save.svg
  package.json
  src/.DS_Store
  src/custom.d.ts
  src/pages/App.tsx
  src/pages/Header.tsx
  src/pages/Login/Login.tsx
  src/types/HeaderTypes.ts
  tsconfig.json
  webpack.common.js
  yarn.lock
Labels: feature

#18 기록한 나라 앨범 마크업 / 기타 설정 수정
  .DS_Store
  .eslintignore
  .eslintrc.js
  .gitignore
  package.json
  src/components/AlbumList.tsx
  src/components/AlbumListItem.tsx
  src/components/AlbumTitle.tsx
  src/components/Layout.tsx
  src/components/NationList.tsx
  src/components/NationListItem.tsx
  src/components/NationListTitle.tsx
  src/custom.d.ts
  src/pages/Album.tsx
  src/pages/Header.tsx
  tsconfig.json
  webpack.common.js
Labels: feature, setting

#20 헤더 스타일 수정
  src/pages/Header.tsx
Labels: improvement

#22 svg icon component 추가 (기존 assets 에서 변경)
  .eslintignore
  .eslintrc.js
  babel.config.js
  package.json
  src/components/FeatureIcon/FeatureIcon.tsx
  src/components/FeatureIcon/index.tsx
  src/components/FeatureIcon/svg/album.svg
  src/components/FeatureIcon/svg/arrow.svg
  src/components/FeatureIcon/svg/cancel.svg
  src/components/FeatureIcon/svg/feed.svg
  src/components/FeatureIcon/svg/index.ts
  src/components/FeatureIcon/svg/mypage.svg
  src/components/FeatureIcon/svg/save.svg
  src/components/FeatureIcon/svg/search.svg
  src/components/NationIcon/NationIcon.tsx
  src/components/NationIcon/index.tsx
  src/components/NationIcon/svg/australia.svg
  src/components/NationIcon/svg/china.svg
  src/components/NationIcon/svg/france.svg
  src/components/NationIcon/svg/hongkong.svg
  src/components/NationIcon/svg/index.ts
  src/components/NationIcon/svg/italy.svg
  src/components/NationIcon/svg/japan.svg
  src/components/NationIcon/svg/korea.svg
  src/components/NationIcon/svg/macau.svg
  src/components/NationIcon/svg/russia.svg
  src/components/NationIcon/svg/singapore.svg
  src/components/NationIcon/svg/spain.svg
  src/components/NationIcon/svg/taiwan.svg
  src/components/NationIcon/svg/thailand.svg
  src/components/NationIcon/svg/uk.svg
  src/components/NationIcon/svg/usa.svg
  src/components/NationIcon/svg/vietnam.svg
  src/pages/Header.tsx
  tsconfig.json
  webpack.common.js
  yarn.lock
Labels: feature, improvement, setting

#25 여행한 나라 찾기 컴포넌트 작업 / 기타 수정
  .eslintrc.js
  src/atoms/addContentState.ts
  src/atoms/addContentViewState.ts
  src/components/DeleteButton.tsx
  src/components/FeatureIcon/FeatureIcon.tsx
  src/components/FeatureIcon/svg/cancel.svg
  src/components/NationFinder/FinderEmptyFallback.tsx
  src/components/NationFinder/FinderNationList.tsx
  src/components/NationFinder/FinderNationListItem.tsx
  src/components/NationFinder/index.tsx
  src/components/NationIcon/NationIcon.tsx
  src/components/NationIcon/svg/australia.svg
  src/components/NationIcon/svg/china.svg
  src/components/NationIcon/svg/france.svg
  src/components/NationIcon/svg/hongkong.svg
  src/components/NationIcon/svg/italy.svg
  src/components/NationIcon/svg/japan.svg
  src/components/NationIcon/svg/korea.svg
  src/components/NationIcon/svg/macau.svg
  src/components/NationIcon/svg/russia.svg
  src/components/NationIcon/svg/singapore.svg
  src/components/NationIcon/svg/spain.svg
  src/components/NationIcon/svg/taiwan.svg
  src/components/NationIcon/svg/thailand.svg
  src/components/NationIcon/svg/uk.svg
  src/components/NationIcon/svg/usa.svg
  src/components/NationIcon/svg/vietnam.svg
  src/components/NationText.tsx
  src/components/SearchEmptyFallback.tsx
  src/components/SearchHeader.tsx
  src/components/SearchInput.tsx
  src/hooks/useAddContent.ts
  src/hooks/useInput.ts
  src/lib/constants.ts
  src/pages/AddContent.tsx
  src/styles/global.ts
  webpack.common.js
Labels: feature

#24 OAuth 로그인 (네이버, 카카오 기본 세팅)
  package.json
  public/index.html
  src/.DS_Store
  src/components/KakaoButton.tsx
  src/components/LoginIcon/LoginIcon.tsx
  src/components/LoginIcon/index.tsx
  src/components/LoginIcon/svg/index.ts
  src/components/LoginIcon/svg/kakao.svg
  src/components/NaverButton.tsx
  src/pages/App.tsx
  src/pages/Login.tsx
  src/pages/Login/Login.tsx
  yarn.lock
Labels: feature

#29 장소 검색하기 컴포넌트 작업
  src/atoms/addContentViewState.ts
  src/components/LocationText.tsx
  src/components/NationFinder/FinderEmptyFallback.tsx
  src/components/NationFinder/FinderNationList.tsx
  src/components/NationFinder/index.tsx
  src/components/NationSearch/NationSearchList.tsx
  src/components/NationSearch/NationSearchListItem.tsx
  src/components/NationSearch/index.tsx
  src/components/NationText.tsx
  src/components/PlaceSearch/PlaceSearchList.tsx
  src/components/PlaceSearch/PlaceSearchListItem.tsx
  src/components/PlaceSearch/index.tsx
  src/components/SearchHeader.tsx
  src/pages/AddStory.tsx
  src/pages/App.tsx
Labels: feature, improvement

#33 마이페이지 이름 수정, 피드백 (마크다운)
  package.json
  src/components/CancelIcon.tsx
  src/components/FeatureIcon/svg/arrow2.svg
  src/components/FeatureIcon/svg/edit.svg
  src/components/FeatureIcon/svg/index.ts
  src/components/LoginIcon/svg/index.ts
  src/components/LoginIcon/svg/naver.svg
  src/components/MyPage/AccountRow.tsx
  src/components/MyPage/ActionModal.tsx
  src/components/MyPage/ActionRow.tsx
  src/components/MyPage/LogoutModal.tsx
  src/components/MyPage/UsernameRow.tsx
  src/components/MyPage/index.ts
  src/pages/App.tsx
  src/pages/Header.tsx
  src/pages/MyPage.tsx
  src/pages/MyPageEdit.tsx
  src/styles/theme.ts
  src/types/HeaderTypes.ts
  src/types/LoginTypes.ts
  yarn.lock
Labels: feature

#39 마이페이지 마크업 완성
  src/.DS_Store
  src/components/CancelIcon.tsx
  src/components/FeatureIcon/svg/index.ts
  src/components/FeatureIcon/svg/line.svg
  src/components/MyPage/AccountRow.tsx
  src/components/MyPage/ActionModal.tsx
  src/components/MyPage/LeaveModal.tsx
  src/components/MyPage/LogoutModal.tsx
  src/pages/MyPage.tsx
  src/styles/theme.ts
Labels: feature, improvement

#42 팝업창 버튼 위치 변경
  src/components/MyPage/ActionModal.tsx
Labels: improvement

#47 이메일 계정 업데이트
  src/pages/MyPage.tsx
Labels: improvement

#44 로그인 페이지 마크업 수정
  src/components/KakaoButton.tsx
  src/components/LoginIcon/svg/index.ts
  src/components/LoginIcon/svg/login.svg
  src/components/LoginIcon/svg/naver2.svg
  src/components/NaverButton.tsx
  src/pages/Login.tsx
Labels: improvement

#46 마이페이지 마크업 수정 (모달 배경 설정)
  package.json
  src/components/MyPage/ActionModal.tsx
  src/components/MyPage/LeaveModal.tsx
  src/components/MyPage/LogoutModal.tsx
  src/components/MyPage/actionModal.css
  webpack.common.js
  yarn.lock
Labels: improvement

#43 앨범 상세 페이지 마크업 / 기타 개선사항
  package.json
  src/components/AddButton.tsx
  src/components/AlbumFeedList/AlbumFeedList.tsx
  src/components/AlbumFeedList/index.tsx
  src/components/AlbumList.tsx
  src/components/AlbumList/AlbumList.tsx
  src/components/AlbumList/AlbumListItem.tsx
  src/components/AlbumList/index.tsx
  src/components/FeatureIcon/svg/index.ts
  src/components/FeatureIcon/svg/no_result.svg
  src/components/NationList/NationList.tsx
  src/components/NationList/NationListItem.tsx
  src/components/NationList/index.tsx
  src/components/NationSearch/NationSearch.tsx
  src/components/NationSearch/index.tsx
  src/components/PlaceSearch/PlaceSearch.tsx
  src/components/PlaceSearch/index.tsx
  src/components/SearchEmptyFallback.tsx
  src/components/SearchHeader.tsx
  src/hooks/useQueryString.ts
  src/pages/AddStory.tsx
  src/pages/Album.tsx
Labels: feature, improvement

#54 리드미 업데이트
  README.md
Labels: documentation

#49 헤더 경로 변경
  src/atoms/myPageState.ts
  src/pages/Header.tsx
  src/pages/MyPage.tsx
Labels: bug, improvement

#55 머지 에러 수정!
  src/components/PlaceSearch/PlaceSearch.tsx
Labels: bug

#56 Type error 수정
  src/pages/AddStory.tsx
  src/pages/Story.tsx
Labels: bug

#57 카카오 로그인 토큰 저장
  src/components/KakaoButton.tsx
  src/components/NaverButton.tsx
  src/utils/request.ts
Labels: feature, improvement

#58 앨범 리스트 API 연결 / 기타 설정 수정
  .eslintrc.js
  package.json
  src/components/AlbumFeedList/AlbumFeedList.tsx
  src/components/AlbumList/AlbumList.tsx
  src/components/AlbumList/AlbumListItem.tsx
  src/components/Layout.tsx
  src/components/NationList/NationList.tsx
  src/components/NationList/NationListItem.tsx
  src/components/NationSearch/NationSearch.tsx
  src/lib/api/album.ts
  src/pages/AddStory.tsx
  src/pages/App.tsx
  yarn.lock
Labels: feature, setting

#61 스토리 디테일, 삭제 기능 구현
  src/atoms/storyState.ts
  src/components/AddImage.tsx
  src/components/Country.tsx
  src/components/Date.tsx
  src/components/Image.tsx
  src/components/ImageInput.tsx
  src/components/ImageList.tsx
  src/components/NationSearch/NationSearch.tsx
  src/components/NationSearch/NationSearchListItem.tsx
  src/components/Place.tsx
  src/components/PlaceSearch/PlaceSearchList.tsx
  src/components/PlaceSearch/PlaceSearchListItem.tsx
  src/components/Story.tsx
  src/components/Title.tsx
  src/hooks/useAddContent.ts
  src/pages/AddStory.tsx
  src/pages/Story.tsx
  src/types/index.ts
  src/utils/request.ts
Labels: feature

#65 앨범 상세 api 연결
  .gitignore
  src/components/AlbumFeedList/AlbumFeedList.tsx
  src/components/AlbumList/AlbumList.tsx
  src/components/Image.tsx
  src/components/ImageInput.tsx
  src/components/NationList/NationList.tsx
  src/components/Story.tsx
  src/lib/api/getCountries.ts
  src/lib/api/getCountryByType.ts
  src/pages/AddStory.tsx
Labels: feature

#69 스토리 생성 API 연결 및 state 수정
  src/atoms/storyState.ts
  src/components/AddImage.tsx
  src/components/Place.tsx
  src/components/PlaceSearch/PlaceSearchList.tsx
  src/components/PlaceSearch/PlaceSearchListItem.tsx
  src/components/Story.tsx
  src/pages/AddStory.tsx
  src/utils/formatter.ts
  src/utils/request.ts
Labels: feature

#76 README 팀원 이미지 추가
  README.md
Labels: documentation

#77 docs : 리드미 팀원 이미지 추가
  README.md
Labels: documentation

#78 헤더 ADD_EDIT 경로 수정
  src/pages/Header.tsx
Labels: improvement

#81 배경 이미지 추가
  src/components/FeatureIcon/svg/index.ts
  src/components/FeatureIcon/svg/save_false.svg
  src/lib/api/getCountries.ts
  src/pages/Header.tsx
  src/styles/global.ts
  tsconfig.json
Labels: update

#82 앨범 이미지 div 백그라운드 제거 / getCountries url 수정 / onClickCustomPlace history.goBack() 으로 수정
  src/components/AlbumList/AlbumListItem.tsx
  src/components/PlaceSearch/PlaceSearch.tsx
  src/lib/api/getCountries.ts
Labels: bug
